#!/usr/bin/env bash
# File 
x=0
for x in {1..100}
do
if (( "$x"%3 == 0 ))
        then
                if (( "$x"%5 == 0 ))
        then
        echo "FizzBuzz"
        fi
        
if (( "$x"%3 == 0 ))
        then 
                echo "Fizz"
elif (( "$x"%5 == 0 ))
then
echo "Buzz"
fi  

fi                
done
