#!/usr/bin/env bash
# Superstitious Numbers
x=1
while [ $x -ne 20 ]
do
	case $x in
		4)
			echo "bad luck from China";;
		9)
			echo "bad luck from Japan";;
		17)
			echo "bad luck from Italy";;
	esac
	x=$(( x+1 ))
	echo $x
done
