#!/usr/bin/env bash
# Superstitious Numbers
x=1
while [ $x -le 20 ];
do
	case [ $x -eq 4 ]
		echo "$x"
		echo "bad luck from China"
esac
case [ $x -eq 9 ]
	echo "$x"
	echo "bad luck from Japan"
esac
case [ $x -eq 17 ]
	echo "$x"
	echo "bad luck from Italy"
esac
done
