#!/usr/bin/env bash
# Hi
hour=0
min=0
while [ $hour -le 12 ]
do
	((hour++))
	echo "Hour: $hour"
	while [ $min -lt 60 ]
	do 
		echo "$min"
		((min++))
		if [ $min -eq 59 ]
		then
			min=$((min=0))
		fi
	done
done
