#!/usr/bin/env bash
# Hi
hour=0
min=1
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	((hour++))
	while [ $min -lt 60 ]
	do 
		echo "$min"
		((min++))
		if [ $min -eq 60 ]
		then
			min=$((min=1))
		fi
	done
done
