#!/usr/bin/env bash
# Task 9
ps -auxf > /var/run/myscript.pid
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINIT
trap 
while true
do
	echo "To infinity and beyond"
	sleep 2
done
