#!/usr/bin/env bash
# Task 11
par=$1
case $par in 
	start)
		bash shell/processes_and_signals/manage_my_process
		echo $$ > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		trap 'echo "manage_my_process stopped"; kill -STOP -- "-$(pgrep manage_my_process)'
		;;	
	esac
