#!/usr/bin/env bash
# Task 11
par=$1
case $par in 
	start)
		./manage_my_process &
		touch /var/run/my_process.pid
		echo $! > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		pkill -f "manage_my_process"
		echo "manage_my_process stopped"
		;;
	restart)
		echo "manage_my_process restarted"
		kill -STOP -- "-$(pgrep manage_my_process)"
		;;	
	*) echo "Usage: manage_my_process {start|stop|restart}"
		;;
	esac
